[tool.poetry]
name = "renovate"
version = "0.1.0"
description = ""
authors = ["Joan Chen <joanchenuk@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
mypy = "0.971"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
